# Generated by Django 3.2.2 on 2021-05-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('profile_type', models.CharField(choices=[('Doctor', 'Doctor'), ('Company', 'Company'), ('Pacient', 'Pacient')], default=('Doctor', 'Doctor'), max_length=7)),
                ('birthday', models.IntegerField(blank=True, null=True, verbose_name='Ziua de nastere')),
                ('phone', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Telefon')),
                ('user_about', models.TextField(blank=True, null=True, verbose_name='Despre tine')),
                ('email', models.TextField(null=True, unique=True, verbose_name='Email')),
                ('username', models.TextField(verbose_name='Username')),
                ('company_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Numele Companiei')),
                ('company_about', models.TextField(blank=True, null=True, verbose_name='Despre Companie')),
                ('company_main_business', models.CharField(blank=True, max_length=150, null=True, verbose_name='Domeniu')),
                ('company_since', models.DateTimeField(blank=True, null=True, verbose_name='Fondarea')),
                ('file', models.FileField(blank=True, upload_to='avatars', verbose_name='Foto')),
                ('is_partner', models.BooleanField(blank=True, default=False, verbose_name='Partener')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
