# Generated by Django 3.2.2 on 2021-05-24 19:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serviceapp', '0001_initial'),
        ('mainapp_label', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('otherinfo', models.CharField(blank=True, max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
            ],
            options={
                'ordering': ('weekday', 'from_hour'),
                'unique_together': {('weekday', 'from_hour', 'to_hour')},
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('study_category', models.CharField(blank=True, max_length=200, null=True)),
                ('study', models.TextField(blank=True, max_length=1000, null=True)),
                ('course', models.TextField(blank=True, max_length=1000, null=True)),
                ('experience_year', models.DateTimeField(auto_now_add=True, null=True)),
                ('publications', models.TextField(blank=True, max_length=500, null=True)),
                ('award_scholarship', models.TextField(blank=True, max_length=1000, null=True)),
                ('member_medical_association', models.CharField(blank=True, max_length=500, null=True)),
                ('google_maps_link', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('children_visit', models.BooleanField(blank=True, null=True)),
                ('description_service_consultation', models.CharField(blank=True, max_length=500, null=True)),
                ('offer_services_text', models.CharField(blank=True, max_length=500, null=True)),
                ('home_visit', models.BooleanField(blank=True, null=True)),
                ('online_consultation', models.BooleanField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('recomandation', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, max_length=90, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate1', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rate2', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rate3', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rate4', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('phone', models.CharField(max_length=12)),
                ('comment', models.CharField(max_length=200)),
                ('final_rate', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('doctor', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=30)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('long_description', models.CharField(blank=True, max_length=1000)),
                ('slug', models.SlugField(max_length=30)),
                ('specialization', models.ManyToManyField(blank=True, to='doctors.Specialization')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='domain',
            field=models.ManyToManyField(blank=True, to='doctors.Domain'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_location', to='doctors.locationdoctor'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='offer_services',
            field=models.ManyToManyField(blank=True, to='serviceapp.Service'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp_label.service_type'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctor',
            name='weekday',
            field=models.ManyToManyField(to='doctors.BusinessWork'),
        ),
    ]
