# Generated by Django 3.2.2 on 2021-05-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_businesswork_weekend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesswork',
            name='from_hour',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='businesswork',
            name='to_hour',
            field=models.TimeField(null=True),
        ),
    ]
