# Generated by Django 3.2.2 on 2021-05-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_auto_20210528_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesswork',
            name='from_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesswork',
            name='to_hour',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
