# Generated by Django 3.2.2 on 2021-05-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_doctor_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.ManyToManyField(blank=True, to='doctors.Specialization'),
        ),
    ]
