# Generated by Django 3.2.2 on 2021-05-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_doctor_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='clinica_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
