# Generated by Django 3.2.2 on 2021-05-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_doctor_clinica_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='experience_timeline',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
