# Generated by Django 3.2.2 on 2021-05-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_auto_20210529_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='procedures',
            field=models.ManyToManyField(blank=True, null=True, to='doctors.Procedure'),
        ),
    ]
