# Generated by Django 3.2.2 on 2021-05-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_alter_doctor_procedures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='procedures',
            field=models.ManyToManyField(blank=True, to='doctors.Procedure'),
        ),
    ]
